import Link from "next/link";
import { ArrowRight, CheckCircle2, FileSpreadsheet, Link2, QrCode } from "lucide-react";
import { SiteHeader } from "@/components/shared/site-header";
import { Button } from "@/components/ui/button";
import { APP_CONFIG } from "@/lib/config";
import { CampaignShowcase } from "@/components/home/campaign-showcase";

export default function Home() {
  return <><SiteHeader /><main><section className="relative overflow-hidden"><div className="absolute inset-0 -z-10 bg-[radial-gradient(circle_at_75%_20%,var(--accent),transparent_36%)]" /><div className="mx-auto grid max-w-6xl gap-12 px-4 py-20 md:grid-cols-[1.05fr_.95fr] md:py-28"><div><h1 className="max-w-2xl text-5xl font-bold leading-[1.04] tracking-tight md:text-6xl">{APP_CONFIG.tagline}</h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted-foreground">Crea una campaña, comparte un enlace y concilia cientos de aportes sin depender de cuentas personales, capturas de WhatsApp ni planillas manuales.</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Button asChild size="lg"><Link href="/dashboard">Crear una campaña <ArrowRight className="size-4" /></Link></Button><Button asChild variant="outline" size="lg"><Link href="/club-los-andes/rifa-viaje-sub-15">Probar demo pública</Link></Button></div></div><CampaignShowcase /></div></section><section className="border-y bg-card"><div className="mx-auto max-w-6xl px-4 py-16"><div className="grid gap-5 md:grid-cols-3">{[{ icon: Link2, title: "Comparte un enlace", text: "Tu campaña queda lista para WhatsApp, Instagram o un código QR." }, { icon: QrCode, title: "Recibe pagos locales", text: "P2P.me conecta el pago local con settlement en USDC sobre Base." }, { icon: FileSpreadsheet, title: "Concilia automáticamente", text: "Cada pago queda asociado a una persona, número y referencia verificable." }].map(({ icon: Icon, title, text }) => <div key={title} className="p-5"><Icon className="size-6 text-primary" /><h2 className="mt-4 text-lg font-semibold">{title}</h2><p className="mt-2 leading-6 text-muted-foreground">{text}</p></div>)}</div></div></section><section className="mx-auto max-w-4xl px-4 py-20 text-center"><CheckCircle2 className="mx-auto size-9 text-success" /><h2 className="mt-4 text-3xl font-bold tracking-tight">La tecnología queda detrás. Tu comunidad solo ve una forma simple de aportar.</h2><p className="mx-auto mt-4 max-w-2xl text-muted-foreground">Fondo usa infraestructura stablecoin para dar trazabilidad, sin convertir la experiencia en una app de crypto.</p></section></main><footer className="border-t py-8 text-center text-sm text-muted-foreground">© 2026 {APP_CONFIG.name} · Construido para la hackathon P2P.me</footer></>;
}
