"use client";
import Link from "next/link";
import { ArrowUpRight, Banknote, Megaphone, Plus, Users } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { formatFiat } from "@/lib/money";
import { useFondoStore } from "@/lib/store";

export function DashboardView() {
  const { campaigns, payments, ready } = useFondoStore();
  const active = campaigns.filter((c) => c.status === "ACTIVE");
  const total = campaigns.reduce((sum, campaign) => sum + campaign.tickets.filter((t) => t.status === "PAID").length * campaign.priceMinor, 0);
  const metrics = [{ label: "Recaudación", value: formatFiat(total), icon: Banknote }, { label: "Pagos", value: campaigns.reduce((n, c) => n + c.tickets.filter((t) => t.status === "PAID").length, 0).toLocaleString("es-AR"), icon: ArrowUpRight }, { label: "Campañas activas", value: active.length.toString(), icon: Megaphone }, { label: "Participantes", value: payments.length ? "327+" : "0", icon: Users }];
  if (!ready) return <div className="animate-pulse space-y-6"><div className="h-10 w-72 rounded bg-muted" /><div className="grid gap-4 md:grid-cols-4">{[1,2,3,4].map((n) => <div key={n} className="h-28 rounded-2xl bg-muted" />)}</div></div>;
  return <div><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><p className="text-sm font-semibold text-primary">Resumen</p><h1 className="mt-1 text-3xl font-bold tracking-tight">Buenas tardes, Club Los Andes</h1><p className="mt-2 text-muted-foreground">Así avanzan tus campañas hoy.</p></div><Button asChild><Link href="/dashboard/campaigns/new"><Plus className="size-4" />Nueva campaña</Link></Button></div><div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon }) => <Card key={label}><CardContent className="flex items-start justify-between p-5"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-secondary text-primary"><Icon className="size-5" /></span></CardContent></Card>)}</div><div className="mt-10 flex items-center justify-between"><h2 className="text-xl font-bold">Tus campañas</h2><span className="text-sm text-muted-foreground">{campaigns.length} en total</span></div><div className="mt-4 grid gap-5 lg:grid-cols-2">{campaigns.map((campaign) => { const sold = campaign.tickets.filter((t) => t.status === "PAID").length; const pct = campaign.ticketCount ? sold / campaign.ticketCount * 100 : 0; return <Card key={campaign.id} className="transition hover:-translate-y-0.5 hover:shadow-md"><CardHeader className="flex-row items-start justify-between"><div><Badge variant="success">Activa</Badge><CardTitle className="mt-3 text-xl">{campaign.title}</CardTitle><p className="mt-1 text-sm text-muted-foreground">{campaign.type === "RAFFLE" ? "Rifa comunitaria" : "Colecta"}</p></div><Button asChild variant="ghost" size="icon"><Link href={`/dashboard/campaigns/${campaign.id}`} aria-label={`Ver ${campaign.title}`}><ArrowUpRight className="size-5" /></Link></Button></CardHeader><CardContent><div className="grid grid-cols-2 gap-4 py-3"><div><p className="text-xs text-muted-foreground">Recaudado</p><p className="mt-1 font-semibold">{formatFiat(sold * campaign.priceMinor)}</p></div><div><p className="text-xs text-muted-foreground">Números</p><p className="mt-1 font-semibold">{sold} / {campaign.ticketCount}</p></div></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{ width: `${pct}%` }} /></div><p className="mt-2 text-right text-xs text-muted-foreground">{pct.toFixed(1).replace(".", ",")}%</p></CardContent></Card>})}</div></div>;
}
